/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "AI/ML Docs",
      items: [{ type: "autogenerated", dirName: "aiml" }],
    },
  ],
};

module.exports = sidebars;